config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get    '/login',  to: 'sessions#authorisation'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resource :profile, only: :show, controller: 'users'

  get '/signup', to: 'users#new', as: 'signup'
  post '/users', to: 'users#create'
  get '/profile', to: 'users#show', as: 'user_root'

  # post "/input_link",to: "input_link#accept_link"
  post "/input_link", to: "dictionaries#create"
  get "/dictionaries/:dict_id", to: "dictionaries#show"
  post "/dictionaries/:dict_id/exclude_words", to: "dictionaries#exclude_words"
  post "/dictionaries/:dict_id/docx", to: "dictionaries#docx"
  resources :dictionaries
end

app/views/shared/_header.html.erb
<nav class="main-nav">
  <% if current_page?(profile_path) %>
    <%= link_to "Главная", root_path, class: "nav-link" %>
    <%= link_to "Личный кабинет", profile_path, class: "nav-link no-color-change" %>
    <% if session[:user_id].present? %>
      <%= button_to 'Выйти', logout_path, method: :delete, class: "btn btn-link nav-link" %>
    <% end %>
  <% else %>
    <%= link_to "Главная", root_path, class: "nav-link" %>
    <%= link_to "Личный кабинет", profile_path, class: "nav-link no-color-change" %>
    <% if session[:user_id].present? %>
      <%= button_to 'Выйти', logout_path, method: :delete, class: "btn btn-link nav-link" %>
    <% else %>
      <%= link_to 'Авторизация', login_path, class: "nav-link" %>
      <%= link_to 'Зарегистрироваться', signup_path, class: "nav-link" %>
    <% end %>
  <% end %>
</nav>